services:
  web:

    build:
      context: ./images
      dockerfile: Dockerfile_php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    environment:
      VAR1: "sóc una pera i estic al docker-compose"
      VAR2: ${VAR2}
    depends_on:
      - db

  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: passwordDeRootQueNoShaDeFerServirMai
      MYSQL_DATABASE: INCIDENCIES
      MYSQL_USER: a24alvsalalv_daw
      MYSQL_PASSWORD: Pryct@Fin@l9923
      LANG: C.UTF-8
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

